### ISSUE TITLE
Zombies Cant Spawn

### ISSUE THREAD

**Issue by ThaWolf324** [TheTurkeyDev/Call_Of_Minecraft-Zombies#101]
When joining the match the zombies disappear like it's in peaceful but it's in hard mode, please help!

**Comment by TheTurkeyDev** [comment]
1. Make sure the world isn't in peaceful mode (I know you said it wasn't but a step to check none the less)
2. Make sure there are no other plugins preventing mob spawning. i,e world protection plugins
3. Mare sure the arena bounds fully encase the arena (i.e the particle box covers the arena)
