### ISSUE TITLE
Doesn't work for Minecraft 1.17.1

### ISSUE THREAD

**Issue by mikayden** [TheTurkeyDev/Call_Of_Minecraft-Zombies#109]
When I start my server the console gives this error the bukkit page says 1.17 is supported _"java.lang.IllegalStateException: Sorry, COM:Z Does not current support server version1.17.1
05.09 06:49:58 [Server] INFO at com.theprogrammingturkey.comz.COMZombies.loadVersionSpecificCode(COMZombies.java:134) ~[comzombies-Universal-2.3.103 (3).jar:?]"_

**Comment by TheTurkeyDev** [comment]
Support for 1.17.1 has been added, just waiting for Curse to approve the new build
