### ISSUE TITLE
Nerf Electric Cherry ?

### ISSUE THREAD

**Issue by TrunGGPablo** [TheTurkeyDev/Call_Of_Minecraft-Zombies#112]
Since the electric cherry is too powerful, maybe can you nerf it to that the Perk will work only if you reload with an empty mag. Shooting a bullet and reload with speed cola trigger Electric Cherry will be so OP.
If you cant seems to do that, can you fix the bug that ElectricC trigger continuously when switching between 2 weapons ? Thanks a lot bro

**Comment by TheTurkeyDev** [comment]
I don't think the first part needs any change. It does seem that the radius is supposed to scale with how many bullets you have shot from the mag, so maybe I can implement that.

For the second part though, yeah that's definitely a bug. Shouldn't be able to trigger the Electric Cherry effect more than once per reload.
