### ISSUE TITLE
Fall damage with players-required arena

### ISSUE THREAD

**Issue by TrunGGPablo** [TheTurkeyDev/Call_Of_Minecraft-Zombies#113]
I create a big arena and set it min-player to 3, when the player join, they took fall damage and drop all inventory but still inside the game. Can you fix it ? I think it is a problem with the countdown system, whenever is not running a countdown, player took damage. Thanks bro

**Comment by TheTurkeyDev** [comment]
I've never had and issues with people taking fall damage. Any console errors?

**Comment by Superfudge247** [comment]
> I create a big arena and set it min-player to 3, when the player join, they took fall damage and drop all inventory but still inside the game. Can you fix it ? I think it is a problem with the countdown system, whenever is not running a countdown, player took damage. Thanks bro

Can you also drop whichj build version of comz your using

**Comment by Superfudge247** [comment]
This can be closed as it's probably the build which bugged when you recoded the player down system
