### ISSUE TITLE
Problem with signs/arena

### ISSUE THREAD

**Issue by EthanA5** [TheTurkeyDev/Call_Of_Minecraft-Zombies#129]
Hi there, I have a problem with my arena. I was adding signs after moving my arena, deleting it, making a new arena, then doing the signs again. It says it is not in an arena and I have a video that showcases this off. I still have no reason why this is happening. Please respond with a solution. https://youtu.be/I4CHuWz2_O4

**Comment by TheTurkeyDev** [comment]
Given I'm seeing no response from the plugin when you enter things like "p1" and "done" I'm thinking you have a bigger underlying issue. What errors are you seeing in your sever console?

**Comment by EthanA5** [comment]
Something about barriers

**Comment by TheTurkeyDev** [comment]
well I need those errors logs in order to further help you

**Comment by EthanA5** [comment]
Here ya go

[19:58:47] [Server thread/WARN]: [COM_Zombies] Task #87 for COM_Zombies
v2.2.86 generated an exception
java.lang.NullPointerException: null
        at
com.theprogrammingturkey.comz.game.managers.BarrierManager.lambda$save$1(BarrierManager.java:101)
~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_311]
        at
com.theprogrammingturkey.comz.game.managers.BarrierManager.save(BarrierManager.java:101)
~[?:?]
        at com.theprogrammingturkey.comz.game.Game.saveGame(Game.java:983)
~[?:?]
        at
com.theprogrammingturkey.comz.game.GameManager.saveAllGames(GameManager.java:78)
~[?:?]
        at
com.theprogrammingturkey.comz.game.Game.addPointOne(Game.java:780) ~[?:?]
        at
com.theprogrammingturkey.comz.game.actions.ArenaSetupAction.onChatMessage(ArenaSetupAction.java:53)
~[?:?]
        at
com.theprogrammingturkey.comz.listeners.PlayerChatListener.lambda$onPlayerChat$1(PlayerChatListener.java:39)
~[?:?]
        at
org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1179)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]

**Comment by EthanA5** [comment]
That was for setting p1 and this when I say done

java.lang.NullPointerException: null
        at
com.theprogrammingturkey.comz.game.managers.BarrierManager.lambda$save$1(BarrierManager.java:101)
~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_311]
        at
com.theprogrammingturkey.comz.game.managers.BarrierManager.save(BarrierManager.java:101)
~[?:?]
        at com.theprogrammingturkey.comz.game.Game.saveGame(Game.java:983)
~[?:?]
        at
com.theprogrammingturkey.comz.game.GameManager.saveAllGames(GameManager.java:78)
~[?:?]
        at
com.theprogrammingturkey.comz.game.Game.gameSetupComplete(Game.java:1328)
~[?:?]
        at
com.theprogrammingturkey.comz.game.actions.ArenaSetupAction.onChatMessage(ArenaSetupAction.java:84)
~[?:?]
        at
com.theprogrammingturkey.comz.listeners.PlayerChatListener.lambda$onPlayerChat$1(PlayerChatListener.java:39)
~[?:?]
        at
org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1179)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]

**Comment by TheTurkeyDev** [comment]
Update the plugin to the latest version

**Comment by EthanA5** [comment]
Thx it worked
