### ISSUE TITLE
Issue - Zombie "Breaking" - Better Barriers

### ISSUE THREAD

**Issue by TTG24** [TheTurkeyDev/Call_Of_Minecraft-Zombies#134]
I have found it nearly impossible to get the zombies to go to certain barriers. I've tried many different spawn configurations from having multiple to having only 1 singular spawnpoint for a barrier. They somehow keep breaking them even if not near them.

The only temporary fix I have found is to keep the spawns close to the barrier (somewhat breaking the immersive-ness) and to use barrier blocks to keep them within a set path. That also ruins gameplay as it will make zombies easily memorable and killable.

I think there should be a radius, in blocks, to how close the zombies should be for them to then start "breaking". I would assume this plugin uses the hardcore zombies and makes selected blocks act like a wooden door. I would not know.

Please fix this, it would make everything so much smoother.

**Comment by TheTurkeyDev** [comment]
See #96 , but yes, the barriers are not very smart currently and start breaking as soon as a zombie is spawned
