### ISSUE TITLE
Please Update to 1.20.2

### ISSUE THREAD

**Issue by DieserEliasYT** [TheTurkeyDev/Call_Of_Minecraft-Zombies#152]
Hello, i really love the Zombies Gamemode of COD and i want to make it on my server. But the plugin gets an error if youre running on 1.20.2

This is the error:
https://mclo.gs/0I8Ra0M

**Comment by TheTurkeyDev** [comment]
As the error logs says 

> 21.11 17:31:43 [Server] INFO java.lang.IllegalStateException: Sorry, COM:Z Does not current support server version1.20.2

Unfortunately I just haven't gotten around to adding 1.20.2 yet

**Comment by DieserEliasYT** [comment]
Will there be support for the 1.20.2 in future? i really want to add it to the server :)

**Comment by TheTurkeyDev** [comment]
There will be when I have the time

**Comment by DieserEliasYT** [comment]
Cant wait for the update haha can i pay you for getting it now? xd

**Comment by TheTurkeyDev** [comment]
No need to pay man. I'll try and  take a look later today

**Comment by TheTurkeyDev** [comment]
[comzombies-Universal-2.3.173.jar.zip](https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/13496106/comzombies-Universal-2.3.173.jar.zip)
Haven't been able to test, but give this a shot and let me know!

**Comment by DieserEliasYT** [comment]
Hey man, thanks for trying to update it. I kinda feel like annoying you haha. I still get an error https://mclo.gs/Iojz1Bt
ChatGPT says this error means its trying to load a class which is not available. "com.theprogrammingturkey.comz.support.support_1_20_R2.NMSUtil_1_20_R2"

**Comment by DieserEliasYT** [comment]
1.12.2-R0.1-SNAPSHOT maybe this spigot api? I use Intellij for my plugins. But I only have basic Java knowledge and this one i used in my 1.20.2 plugin pom.xml

**Comment by TheTurkeyDev** [comment]
Ah I found my isssue. Give this a try
[comzombies-Universal-2.3.174.jar.zip](https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/13502658/comzombies-Universal-2.3.174.jar.zip)

**Comment by DieserEliasYT** [comment]
hey man i fucking love you!! Plugin loads without a single error!

**Comment by DieserEliasYT** [comment]
Im just testing it out and players wont take damage from zombies

**Comment by TheTurkeyDev** [comment]
Any errors in the console?

**Comment by DieserEliasYT** [comment]
https://laby.net/post/50c61008 and the tablist is broken, when i leave the game my tablist is still broken and the playername is displayed all white

**Comment by TheTurkeyDev** [comment]
Check the whole console log, even from when the server first started. It sounds like a larger error that has broken the plugin as a whole

**Comment by DieserEliasYT** [comment]
there was no error but a message when restarting the plugin

29.11 17:37:36 [Server] INFO DieserEliasYT issued server command: /plugman restart COM_Zombies
29.11 17:37:36 [Server] INFO Disabling COM_Zombies v2.3.174
29.11 17:37:36 [Server] INFO [COM_Zombies] has been disabled!
29.11 17:37:36 [Server] INFO Enabling COM_Zombies v2.3.174
29.11 17:37:36 [Server] WARN Enabled plugin with unregistered ConfiguredPluginClassLoader COM_Zombies v2.3.174
29.11 17:37:36 [Server] INFO [COM_Zombies] Version info | MC: 1.20.2 | Bukkit: git-Paper-297 (MC: 1.20.2) & 1.20.2-R0.1-SNAPSHOT | CB: org.bukkit.craftbukkit.v1_20_R2
29.11 17:37:36 [Server] INFO Kit Weapon: is an invalid gun name!
29.11 17:37:36 [Server] INFO Perk: is an invalid perk name!
29.11 17:37:36 [Server] INFO [COM_Zombies] Vault hook enabled!
29.11 17:37:36 [Server] INFO Successfully registered internal expansion: comz [2.3.174]
29.11 17:37:36 [Server] INFO [COM_Zombies] has been enabled!
29.11 17:37:36 [Server] Startup Done loading arenas!

**Comment by TheTurkeyDev** [comment]
Try restarting the server completely instead of just reloading it

**Comment by DieserEliasYT** [comment]
No error just the start message

29.11 17:42:29 [Server] INFO Enabling COM_Zombies v2.3.174
29.11 17:42:29 [Server] INFO [COM_Zombies] Version info | MC: 1.20.2 | Bukkit: git-Paper-297 (MC: 1.20.2) & 1.20.2-R0.1-SNAPSHOT | CB: org.bukkit.craftbukkit.v1_20_R2
29.11 17:42:29 [Server] INFO [COM_Zombies]  Vault hook enabled!
29.11 17:42:29 [Server] INFO Successfully registered internal expansion: comz [2.3.174]
29.11 17:42:29 [Server] INFO [COM_Zombies] has been enabled!

**Comment by TheTurkeyDev** [comment]
So even after completly restarting the server the problem still persists?

**Comment by DieserEliasYT** [comment]
ohhh now it works but im using multiverse inventories and it cleared my inventory on other world lol

**Comment by DieserEliasYT** [comment]
the plugin works. for example: i have a citybuild server with multiverse inventorys and i just joined a game cia command, everything worked even the damage on players but after the game i get teleported where i run the join command (in citybuild) with an empty inventory. but i have an idea. i create a world where you can join the arenas and with luckperms i can give them "per world permissions". I think that should fix the inventory clear cause in that world with the zombie games there is another inv and then players inventory cant get cleared

**Comment by DieserEliasYT** [comment]
okay i figured out i only take damage on bedrock edition. i was testing it out on bedrock edition when i restarted the game cause my minecraft client wont let me load the servers but then i joined with bot versions and bedrock players take damage but java wont
