### ISSUE TITLE
Guns don't do damage

### ISSUE THREAD

**Issue by basrodw** [TheTurkeyDev/Call_Of_Minecraft-Zombies#161]
When i shoot my guns they do any damage to the zombies only my knife can kill them. All seen in the attached yt link. https://youtu.be/oAhO8uiZG_w

Pls help as i am wanting to record a video for my yt channel on this ASAP and it took me hours to set it all up.

Thanks

**Comment by TheTurkeyDev** [comment]
Are there any errors in your server console?

**Comment by basrodw** [comment]
I don't think so. But how would i double check that? 
(p.s. thanks for getting back to me so quick)

**Comment by TheTurkeyDev** [comment]
You would check the console for any errors. Not sure how to best describe it beyond that. Really just large bits of text that don't look like normal logs. You can also upload all the logs to something like pastebin and I can look through them

**Comment by basrodw** [comment]
Sweet, this is my hastebin link for my latest log. https://hastebin.com/share/okukexamen.css

**Comment by TheTurkeyDev** [comment]
I see lots of errors in there which explains the issues. I've heard people have had issues with this plugin on paper servers in the past. I don't know why Paper breaks things, but that may be your issue

**Comment by basrodw** [comment]
Okay, so what can i do to  get this working? is there something else i can use other than paper?

**Comment by TheTurkeyDev** [comment]
You can use Spigot

**Comment by basrodw** [comment]
Thanks man! it worked with Spigot. 

Here's the video link if you or anyone was interested in watching: https://youtu.be/UBFEY5FH56g

Also i did notice that there were no power ups when i played, any idea how to fix that?

**Comment by TheTurkeyDev** [comment]
power up drop chance can be changed in the config
