### ISSUE TITLE
Weapon Signs Prices Instead of Ammo.

### ISSUE THREAD

**Issue by BeariliGaming** [TheTurkeyDev/Call_Of_Minecraft-Zombies#25]
Weapon signs cannot be edited well atm. It would be nice for a player just to see "&cFIVE-SEVEN: 500" on a sign. Simple and clean.

But thats not to big of an issue.

The biggest thing is the ammo being shown rather than the price of the weapon. I have had a couple players die already by running to a weapon on the wall, tried to click it multiple times only to realize the "200/100" was ammo and not 200 points. Then get trapped beside the weapon and die. Then rage quit.... lol Just a tiny bit frustrating for newer players.

**Comment by TheTurkeyDev** [comment]
The 200/100 should refer to the gun cost/refill cost, i.e 200 to buy the bun, 100 to refill ammo

**Comment by BeariliGaming** [comment]
Oh, in that case. All the weapons are "200/100"

**Comment by TheTurkeyDev** [comment]
That should be fixed in the latest version. Try remaking the signs

**Comment by BeariliGaming** [comment]
I just remade my B23R sign:
[Zombies]
Gun
B23R
600

It still came out as 200/100... then i went into game and played. It also costed me 200. So still stuck on 200/100 i believe

**Comment by BeariliGaming** [comment]
Also, can we edit the refill price too? Should I have tried:
[Zombies]
Gun
B23R
600/200

**Comment by TheTurkeyDev** [comment]
Yes, sorry. You have to enter in both values, so do try 600/200
