### ISSUE TITLE
Barrier Spawn Block Interaction Error

### ISSUE THREAD

**Issue by Zakkary19** [TheTurkeyDev/Call_Of_Minecraft-Zombies#32]
I have spoken to you about this error on discord, but to recap.

I get this error ---- > https://pastebin.com/YNXvhukz

This happens everytime I do the "/zombies addbarrier Arena1" command.
I can then click on the barrier block, type done, click on the sign, type done. 
However, when I go to click on the spawn block (end portal), nothing happens and it throws the error in console every time i click. Only way to escape this is by typing cancel or by leaving the server. 

If you need anymore information, I will be happy to provide. Hell, if you would like to come on my server and reproduce it for yourself, you are more than welcome to!

**Comment by Zakkary19** [comment]
Also note, my server is running Paper version git-Paper-130 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by TheTurkeyDev** [comment]
I will say, the version you have doesn't 100% work with spigot 1.16.1

**Comment by TheTurkeyDev** [comment]
Should be fixed in the new version!
