### ISSUE TITLE
1.16.4?

### ISSUE THREAD

**Issue by Firewithfire115** [TheTurkeyDev/Call_Of_Minecraft-Zombies#33]
I downloaded the plugin, built a map, and used the very simple system you designed to set it up, all seems to work fine until a player types /zombies join, in which they are placed in the lobby but given the error message "An internal error occurred." 

Could this be because your plugin says only up to 1.16.3?  If so, when is the 1.16.4 version coming?  If not, why am I getting this error message?

**Comment by TheTurkeyDev** [comment]
Yes, the is no 1.16.4 version out currently. One is being worked on, but it contains a big config rewrite hence why it isn't out yet

**Comment by Firewithfire115** [comment]
I'm not even sure what 1.16.4 adds to the game...  Such a useless update.  Thank you for your work, I'm sure the plugin will be amazing once it is updated to 1.16.4.  No rush, but any thoughts as to when it might be ready?

**Comment by TheTurkeyDev** [comment]
Now available on Curse!
