### ISSUE TITLE
1.8?

### ISSUE THREAD

**Issue by sinender** [TheTurkeyDev/Call_Of_Minecraft-Zombies#35]
Is the latest version compatible with 1.8 and if it is not is it possible to be compatible?

**Comment by TheTurkeyDev** [comment]
That latest version is not compatible with 1.8, sorry

**Comment by sinender** [comment]
Is it at all possible to compile it as 1.8?

**Comment by TheTurkeyDev** [comment]
You would need to switch the spigot version to 1.8 and then fix all the build errors. I don't have the time to support everything. I mainly stick to the latest version. As of the moment, there's no solution for supporting multiple versions at once

**Comment by TheTurkeyDev** [comment]
tl;dr Yes, but it takes a little work

**Comment by sinender** [comment]
The current problem I'm having right now is the plugin.yml not being there the build hasnt had any errors

**Comment by TheTurkeyDev** [comment]
You may need to redo that file. I'm pretty sure the specs have changed for it since 1.8

**Comment by sinender** [comment]
There is no plugin.yml currently in the code, could you please send me that file?

**Comment by TheTurkeyDev** [comment]
It's right here https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/blob/dev_1.15.x/src/main/resources/plugin.yml

**Comment by sinender** [comment]
Oh I see

**Comment by Superfudge247** [comment]
This should also be closed please don't shoot me sorry
