### ISSUE TITLE
Support for 1.16.4?

### ISSUE THREAD

**Issue by HoneyMustardAdmin** [TheTurkeyDev/Call_Of_Minecraft-Zombies#36]
When I updated my server to 1.16.4 the plugin stopped working, I noticed on the plugin page that it goes to 1.16.3 so I figured that would be the problem. 

Any thoughts as to when you’ll get it up to 1.16.4, if ever? 

No pressure my guy, it’s a gorgeous plugin that runs smoother than a greased up pig on a slip n slide.

**Comment by TheTurkeyDev** [comment]
There's a beta for it available on my Discord. There are just a lot of bigger code base changes wrapped into this that it's just taking a while to get it all 100% and tested enough where I'm happy. It's close though

**Comment by TheTurkeyDev** [comment]
Duplicate of #33
