### ISSUE TITLE
Mystery Box Bug

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#41]
I found a bug where if you have a multiplayer game it allows you to take other players weapons from the mystery box also sometimes even in a single player game the player can not take the weapon at all and it just times out the gun hope this can be fixed thanks

**Comment by Superfudge247** [comment]
I'd like to add my server is running on 1.16 as this will help xD

**Comment by TheTurkeyDev** [comment]
Can you provide the version of the plugin and any errors in the console?

**Comment by Superfudge247** [comment]
Sorry for the slow reply we also found another bug when someone try's to take the weapon from the box and it refuses to give them it if they spam trying to grab the weapon it crashes the server I would provide crash information but my server didn't generate a log also I am using the Latest version of Spigot 1.16.1

**Comment by TheTurkeyDev** [comment]
Unfortunately there's not much I can do without a log

**Comment by Superfudge247** [comment]
@TheTurkeyDev I will try and replicate the bug and keep an eye out for a log :)

**Comment by Superfudge247** [comment]
I found a log (https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/5844848/2021-01-19-3.log)

**Comment by Superfudge247** [comment]
I am using the latest version of your plugin available to download from bukkit

**Comment by TheTurkeyDev** [comment]
I see the error. Will look around too see if I can figure out the cause and get a fix
