### ISSUE TITLE
Grenades are infinite

### ISSUE THREAD

**Issue by Firewithfire115** [TheTurkeyDev/Call_Of_Minecraft-Zombies#42]
Grenades and Monkey Bombs are able to be spammed infinitely, making them game breaking.

**Comment by TheTurkeyDev** [comment]
Spammed infinitely how?

**Comment by Firewithfire115** [comment]
My players can get grenades and monkey bombs from a box and throw them basically as fast as they can click, is this an issue on my end?

**Comment by TheTurkeyDev** [comment]
If they don't run out yes. You should only be getting 4 per mystery box.

**Comment by Firewithfire115** [comment]
Any thoughts as to why?

**Comment by TheTurkeyDev** [comment]
As to why they are infinite? Sounds like something is causing a bad interaction. Not sure what else to say

**Comment by Superfudge247** [comment]
I can second the infinite grenades and monkey bombs I have the same issue happening where you can spam throw them it shows you have 4 in your hot bar however they never deplete when thrown

**Comment by TheTurkeyDev** [comment]
I will look into this more then

**Comment by TheTurkeyDev** [comment]
v2.2.64 Was just submitted to Curse fixing this bug. If the issue still persists please reopen this ticket!
