### ISSUE TITLE
LOOSE YOUR WEAPON IN SLOT 1 AFTER BEING REVIVED

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#43]
so as you know when your put into last stand you get the m1911 however when the player is revived they don't receive the weapon they had prior to being downed

**Comment by Superfudge247** [comment]
I am using the latest version of your plugin available to download from bukkit

**Comment by TheTurkeyDev** [comment]
As with all issues, any error logs around this one?

**Comment by Superfudge247** [comment]
This would have been the console log when the issue occurred (https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/5845177/2021-01-20-4.log) I also noticed a bug with sneak/aiming you can aim when in lobby but you get stuck in aim mode and can't toggle out of it and then when tped to the arena it puts you out of the aim mode and no longer can be used this error only occurs when you have the aim texture on inside the main config

**Comment by TheTurkeyDev** [comment]
Feel free to make a another ticket for that to help me track the scoping issue

**Comment by TheTurkeyDev** [comment]
v2.2.64 Was just submitted to Curse with a possible fix for this but, but not certain. Leaving this ticket open for the mean time, but if no one reports further issues I will close this
