### ISSUE TITLE
Aim Bug

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#44]
noticed a bug with sneak/aiming you can aim when in lobby but you get stuck in aim mode and can't toggle out of it and then when teleported to the arena it puts you out of the aim mode and no longer can be used this error only occurs when you have the aim texture enabled inside the main config
[2021-01-20-4.log](https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/5852949/2021-01-20-4.log)

**Comment by TheTurkeyDev** [comment]
v2.2.64 Was just submitted to Curse fixing this bug. If the issue still persists please reopen this ticket!
