### ISSUE TITLE
Mobs unable to pickup items server-wide

### ISSUE THREAD

**Issue by Aggnomelord** [TheTurkeyDev/Call_Of_Minecraft-Zombies#46]
Hi, absolutely love the plugin. 
I noticed while trying to make a farm with foxes that they were unable to pickup items. So I loaded up a fresh server with all the plugins I have, deleting plugins until I identified this one as the cause. I did some testing and with only this plugin enabled on a fresh install, both foxes and zombies are unable to equip items at all. My guess is whatever prevents the zombies in the arena from picking up items, applies server-wide and to all mobs. As far as I can see, no error messages are generated anywhere to send so I don't have much more information to offer than this. Thanks for putting in the work to create such a cool plugin.

**Comment by TheTurkeyDev** [comment]
Hmmm. Interesting. I'll have to look into this!

**Comment by Firewithfire115** [comment]
Oh well that explains that issue on my server, too.

**Comment by TheTurkeyDev** [comment]
v2.2.64 Was just submitted to Curse fixing this bug. If the issue still persists please reopen this ticket!
