### ISSUE TITLE
Economy Feature not working

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#48]
I have both vaults and essentials installed both are using the latest versions however at the end of the match I am not being awarded the money I have set in the config using 1.16 version of spigot and COM: Zombies v2.2.63

**Comment by TheTurkeyDev** [comment]
I will leave these open for now, but once the new build is approved, please test with that and let me know if the issues still persist

**Comment by Superfudge247** [comment]
> I will leave these open for now, but once the new build is approved, please test with that and let me know if the issues still persist

Using Spigot 1.16
Latest Dev Build comzombies-Universal-2.2.65.jar

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.74
