### ISSUE TITLE
Game ended couldn't use any other commands

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#49]
after the game ended we were teleported back to our previous positions however we couldn't use commands it kept saying in the chat that we were still in a game we had to use /z leave in order for it to take into account we were not in a game 

good to knows 
we died on a dog round "could be linked?"
The plugin had told us the game ended
We are using COM: Zombies v2.2.63

 running in spigot 1.16

**Comment by Superfudge247** [comment]
[2021-01-29-3.log](https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/5896778/2021-01-29-3.log)

**Comment by Superfudge247** [comment]
[latest.log](https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/5896788/latest.log)

**Comment by Superfudge247** [comment]
#67

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.74
