### ISSUE TITLE
Issue with door removal

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#50]
The removal process seems fine however it can bug out and even after removing the doors you wanted to remove and then typing "done" all other doors signs still appear to have the remove door text I have tried to do commands such as /z enable arena however still get the problem I go back into removal mode and do "done" again and it still seems to be bugged if I restart the server the signs are no longer buyable doors just signs with red text

**Comment by Superfudge247** [comment]
if I enter the match and then leave again it changes the signs back to the doors and points signs

**Comment by TheTurkeyDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Door removal](https://trello.com/c/6as0fVFQ/89-door-removal)
