### ISSUE TITLE
Items and Gun can be moved into off hand by pressing f

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#52]
Items and Gun can be moved into off hand by pressing f

Using 1.16 Spigot
comzombies-Universal-2.2.63.jar

it don't allow you to duplicate however you can make a good mess of your hud

**Comment by TheTurkeyDev** [comment]
Found this a while back myself, but I forgot about it till now

**Comment by Superfudge247** [comment]
> Found this a while back myself, but I forgot about it till now

it was quite funny for us to be honest xD

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.74
