### ISSUE TITLE
Arenas not being recognised

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#53]
After having more than 2 arenas the plugin has had some form of leak as no matter how many times I restore the previous working third arena via my backup arena.json I restart the server and still the plugin is sure that all arenas that previously worked don't exist 

Using Spigot 1.16
comzombies-Universal-2.2.63.jar

**Comment by TheTurkeyDev** [comment]
Possibly linked to #50
