### ISSUE TITLE
Please add the ability to disable dogs in the next available update!

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#54]
The game is almost unplayable dogs/wolfs ain't even hard they are just annoying they are way too fast even with stamin up and the hit box for wolfs makes them near impossible to kill with raytracing they have so many spawning bugs I would rather disable them I even have a ray gun and if your even slightly unlucky that's the end of the game it feels very cheap to loose to a dog I understand call of duty has hellhounds but the hitbox is just tragic great idea tho

**Comment by TheTurkeyDev** [comment]
Yeah Hell hound rounds need to be configurable.

**Comment by TheTurkeyDev** [comment]
Since you've been submitting all these ticket and helping me a ton by doing so, mind joining my Discord? There I can probably talk to you and work things out quicker and I can also give you dev builds since Curse is being atrociously slow. discord.gg/7Xj24pn

**Comment by Superfudge247** [comment]
I joined your discord and sent you a dm I hope that's okay if not I'll keep it inside your discord in future hope that's good 😊👍

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.74
