### ISSUE TITLE
Max Ammo doesn't replenish grenades or monkey bombs

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#60]
I am unsure if you intended for Max Ammo to have this function however I thought it was worth mentioning 

Max Ammo doesn't replenish grenades or monkey bombs you have to get them back out the box and they are really really hard to pull xD they are like ray guns which I can understand with Monkeys but obviously grenades meh :)

Using Spigot 1.16
COMZ DEV comzombies-Universal-2.2.65.jar

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.86
