### ISSUE TITLE
Minor Bug Walking on a pressure plate can make a gun shoot

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#62]
While you have your gun in my hand if you walk over a pressure plate it will randomly shoot it has confused so many people I have met I don't know if you can do anything regarding this but I just thought it might be good for those planning to have some form of redstone doors that didn't use buttons

Using Spigot 1.16
COMZ DEV comzombies-Universal-2.2.65.jar

**Comment by TheTurkeyDev** [comment]
O.o

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.86
