### ISSUE TITLE
Mystery Box can give players the exact same weapon as slot 1 or 2

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#65]
Mystery Box can give players the exact same weapon as slot 1 or 2 allowing them to run an entire game with two Rayguns! or two LSats makes the game very broken at Early and Late Rounds

Using Spigot 1.16
COMZ DEV comzombies-Universal-2.2.65.jar

**Comment by TheTurkeyDev** [comment]
Added in v2.2.86
