### ISSUE TITLE
Mystery Box never has Teddy Bear/Totem of Undying

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#66]
Inside my game today I hit the same Mystery Box Location around 30/40 times not a single sign of the Toten of Undying/Teddy Bear inside my Arenas.yml I have it set to an 85% chance to spawn a Teddy

Using Spigot 1.16
COMZ DEV comzombies-Universal-2.2.65.jar

**Comment by TheTurkeyDev** [comment]
Sorry, the words are a bit misleading. They are actually 1 in x config options. so if you have 85, it's a 1 in 85 chance, not 85%. I wish json had comments 🙃

**Comment by Superfudge247** [comment]
Haha well atleast it's not a bug 🤣👍
