### ISSUE TITLE
1.12.2?

### ISSUE THREAD

**Issue by bz001** [TheTurkeyDev/Call_Of_Minecraft-Zombies#69]
This plugin is really great! So when will this plugin support 1.12.2? I really like this plugin!

**Comment by TheTurkeyDev** [comment]
Related to #35 , but essentially there are no plans on supporting 1.12 at the moment. Just by nature of the changes made to Minecraft, I would need to sort a lot of things out for the plugin to be compatible with versions prior to 1.14 and 1.13

**Comment by bz001** [comment]
Ok,fine.But I really need it, so when do you plan to add support to 1.12.2. I'll take my time to wait for it.

**Comment by TheTurkeyDev** [comment]
Sorry I don't have any sort of timeline at the moment

**Comment by Superfudge247** [comment]
recommend closing this since it's be answered and it's clogging up for no reason xD

**Comment by ikbenignace** [comment]
Close this issue :)
