### ISSUE TITLE
Electric Cherry Consumes ammo from Gun

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#74]
When reloading with electric cherry it has a chance to use the thunder/lightning strike on zombies however when this occurs it consumes a whole mag from the weapon I am using for example if I'm using an RPD it will remove 100 bullets when I spam reload it emptys my gun in seconds

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.86
