### ISSUE TITLE
"BUG REPORT" Perms have broken!

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#81]
I was on discord and a dude had issues with perms I thought for a second... and I didn't think there was an issue with them
however I went to check them out and it turns out that perms aren't working I gave myself the perms "zombies.join" and "zombies.join.mapname" however still I couldn't join the arena and the only time I can is when I am op

**Comment by Superfudge247** [comment]
[2021-03-03-2.log](https://github.com/TheTurkeyDev/Call_Of_Minecraft-Zombies/files/6076482/2021-03-03-2.log)

**Comment by Superfudge247** [comment]
![Untitled](https://user-images.githubusercontent.com/67713088/109817474-df7dd080-7c29-11eb-9f20-231daa60d2c4.png)

**Comment by TheTurkeyDev** [comment]
Need to implement `zombies.join` to work for all arenas

**Comment by TheTurkeyDev** [comment]
Should now be addressed by 0efe777

**Comment by TheTurkeyDev** [comment]
Fixed in v2.2.86
